name: Update LeetCode Count

on:
  push:
    branches:
      - main

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get install curl

    - name: Get LeetCode solved count from API
      run: |
        # Set the LeetCode username
        username="spirita1204"
        
        # Call the API and get the total solved count
        response=$(curl -s "https://leetcode-stats-api.herokuapp.com/$username")
        
        # Extract totalSolved count from the API response
        solved_count=$(echo "$response" | jq -r '.totalSolved')
        
        # Update README.md with the new solved count
        if [ "$solved_count" != "null" ]; then
          echo "Updating solved count in README.md..."
          sed -i "s/LeetCode%20Solved-[0-9]\+/LeetCode%20Solved-${solved_count}/" README.md
        else
          echo "Failed to retrieve solved count."
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your_email@example.com"
        git add README.md
        git commit -m "Update LeetCode solved count"
        git push
